[build-system]
requires = [
    "wheel",
    # Check the updated version pinning requirements in:
    # https://github.com/pypa/setuptools_scm
    "setuptools",
    "setuptools_scm[toml]",
    "cmake_build_extension",
    "numpy",
]
build-backend = "setuptools.build_meta"
