name: Build wheels

on: "workflow_dispatch"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-20.04,
          windows-2019,
          macOS-11,
        ]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.12.0

      - name: Build wheels
        run: python -m cibuildwheel --arch auto64 --output-dir wheelhouse
        env:
          CIBW_TEST_COMMAND: "python {project}/test/python/test_docs.py"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl